apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sgi
resources:
  - ../base/tercers-api
patches:
  - path: tercers-api-values.yaml
    target:
      kind: HelmRelease
      name: tercers-api-release