apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tercers-api-release
  namespace: sgi
spec:
  releaseName: hercules-udl-mi-monorepo
  chart:
    spec:
      chart: helm/hercules-udl-mi
      sourceRef:
        kind: GitRepository
        name: tercers-api-repo
  interval: 5m
  timeout: 2m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    replicaCount: 1